apiVersion: v1
kind: Pod
metadata:
  name: {{ include "mtkpi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mtkpi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  restartPolicy: Always
  containers:
    - name: mtkpi
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: http
          containerPort: 7681
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mtkpi.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "mtkpi.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
