apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mtkpi
  labels:
    app: mtkpi
spec:
  selector:
    matchLabels:
      app: mtkpi
  template:
    metadata:
      labels:
        app: mtkpi
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: mtkpi
        image: r0binak/mtkpi:v1.5
        securityContext:
          privileged: true
      ports:
      - name: mtkpi-hostport
        containerPort: 7681
      tolerations:
        - key: ""
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: mtkpi
spec:
  type: NodePort
  externalTrafficPolicy: Local 
  selector:
    app: mtkpi 
  ports:
  - name: mtkpi-port
    protocol: TCP
    port: 7681
    targetPort: 7681
    nodePort: 31681
