apiVersion: v1
kind: Namespace
metadata:
  name: pentest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtkpi-sa
  namespace: pentest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mtkpi-role
  namespace: pentest
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtkpi-bind
  namespace: pentest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mtkpi-role
subjects:
- kind: ServiceAccount
  name: mtkpi-sa
  namespace: pentest
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mtkpi
  namespace: pentest
  labels:
    app: mtkpi
spec:
  selector:
    matchLabels:
      app: mtkpi
  template:
    metadata:
      labels:
        app: mtkpi
    spec:
      serviceAccountName: mtkpi-sa
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: mtkpi
        image: r0binak/mtkpi:v1.5
        securityContext:
          privileged: true
      ports:
      - name: mtkpi-hostport
        containerPort: 7681
      tolerations:
        - key: ""
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: mtkpi
  namespace: pentest
spec:
  type: NodePort
  externalTrafficPolicy: Local 
  selector:
    app: mtkpi 
  ports:
  - name: mtkpi-port
    protocol: TCP
    port: 7681
    targetPort: 7681
    nodePort: 31681
