apiVersion: v1
kind: ServiceAccount
metadata:
  name: pentest-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pentest-role
  namespace: kube-system
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pentest-bind
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: pentest-sa
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pentest-role
---
apiVersion: v1
kind: Pod
metadata:
  name: pentest
  namespace: kube-system
  labels:
    app: pentest
spec:
  serviceAccountName: pentest-sa
  containers:
  - name: pentest
    image: alpine
    securityContext:
      privileged: false
    command: ["/bin/sh", "-c", "apk add --no-cache kubectl && kubectl auth can-i --list -n kube-system && kubectl get secrets -n kube-system && sleep 3600"]
